{"name": "Проверяем авторизацию созданного полььзователя, с неверным логином и паролем, ожидаем статус-код 401", "status": "passed", "steps": [{"name": "Отправляем запрос, на авторизацию пользователя", "status": "passed", "parameters": [{"name": "auth_data", "value": "{'email': 'datatest2@mail.ru', 'password': 'Qwe123'}"}], "start": 1736186802091, "stop": 1736186802416}], "parameters": [{"name": "auth_data", "value": "{'email': 'datatest2@mail.ru', 'password': 'Qwe123'}"}], "start": 1736186802090, "stop": 1736186802418, "uuid": "b2f83226-f3c4-4cea-9202-77dee5a2c25d", "historyId": "ae0ce4ee556e1abf588a995203863ff6", "testCaseId": "f32a3d8ccf9fa3a015cd458bd6bb6194", "fullName": "tests.test_user.TestUser#test_auth_user_invalid_login_password", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_user"}, {"name": "subSuite", "value": "TestUser"}, {"name": "host", "value": "swiftjointpc"}, {"name": "thread", "value": "1840-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_user"}]}